import { githubActivity, insights, quickActions, recentStudy, upcomingEvents } from "../mock-data";
import { DashboardCard, SectionHeader } from "./dashboard-card";
import { Icon } from "./icon";
import { Timeline } from "./timeline";

export function TodayFocus() {
  return <DashboardCard className="focus-card min-h-[304px]"><div className="flex h-full flex-col"><SectionHeader eyebrow="Today's focus" title="Data Structures" action={<span className="status-badge"><span className="size-1.5 rounded-full bg-accent" />Next at 10:00</span>} /><p className="mt-2 max-w-xl text-[13px] leading-6 text-text-secondary">Review trees and traversal methods before your lecture. Your first deadline follows tomorrow afternoon.</p><div className="mt-auto grid grid-cols-1 gap-px overflow-hidden rounded-xl border border-border bg-border sm:grid-cols-3"><FocusMetric label="Next class" value="10:00" detail="Lecture Hall B" /><FocusMetric label="Next deadline" value="Tomorrow" detail="Calculus problem set" /><FocusMetric label="Today" value="3 events" detail="Last event at 15:00" /></div></div></DashboardCard>;
}

function FocusMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="bg-surface px-4 py-4"><p className="text-xs text-text-tertiary">{label}</p><p className="mt-1.5 text-[15px] font-semibold text-text-primary">{value}</p><p className="mt-1 truncate text-xs text-text-secondary">{detail}</p></div>; }

export function InsightsCard() { return <DashboardCard><SectionHeader eyebrow="Intelligence" title="AI insights" /><div className="mt-6 space-y-1">{insights.map((insight, index) => <div className="group flex gap-3 rounded-xl px-2 py-3 transition hover:bg-surface-hover" key={insight}><span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-accent/70" /><p className="text-[13px] leading-5 text-text-secondary">{insight}</p>{index === 0 && <Icon name="arrow" size={14} className="ml-auto mt-0.5 shrink-0 text-text-tertiary opacity-0 transition group-hover:opacity-100" />}</div>)}</div></DashboardCard>; }

export function MockUpcoming() { return <DashboardCard><SectionHeader eyebrow="This week" title="Coming up" /><Timeline events={upcomingEvents} /></DashboardCard>; }

export function GithubCard() { return <DashboardCard><SectionHeader eyebrow="Coursework" title="GitHub activity" action={<Icon name="branch" size={16} className="text-text-tertiary" />} /><p className="mt-6 truncate text-[13px] font-medium text-text-primary">{githubActivity.repository}</p><div className="mt-4 flex items-center gap-5 text-xs text-text-secondary"><span><strong className="font-semibold text-text-primary">{githubActivity.openPullRequests}</strong> open PRs</span><span>Updated 2h ago</span></div><div className="mt-5 border-t border-border pt-3">{githubActivity.recentCommits.map((commit) => <div className="flex items-center gap-3 py-2 text-xs" key={commit}><span className="size-1 rounded-full bg-text-tertiary" /><span className="min-w-0 flex-1 truncate text-text-secondary">{commit}</span><span className="font-mono text-text-tertiary">8f2a</span></div>)}</div></DashboardCard>; }

export function StudyCard() { return <DashboardCard><SectionHeader eyebrow="Recent" title="Study progress" /><div className="mt-4 divide-y divide-border">{recentStudy.map((item) => <div className="flex items-center gap-3 py-3" key={item.subject}><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-surface-hover text-text-secondary"><Icon name="note" size={15} /></span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">{item.subject}</p><p className="truncate text-xs text-text-tertiary">{item.detail}</p></div><span className="text-xs text-text-tertiary">{item.time}</span></div>)}</div></DashboardCard>; }

export function QuickActions() { return <section><SectionHeader title="Quick actions" /><div className="grid grid-cols-2 gap-3">{quickActions.map((action) => <button className="quick-action group" key={action.label}><Icon name={action.icon} size={16} /><span>{action.label}</span><Icon name="arrow" size={13} className="ml-auto text-text-tertiary opacity-0 transition group-hover:opacity-100" /></button>)}</div></section>; }

export function ChatEntry() { return <DashboardCard className="ask-card"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-accent-soft text-accent"><Icon name="spark" size={16} /></span><div className="min-w-0 flex-1"><p className="text-[13px] font-medium text-text-primary">Ask Zury...</p><p className="truncate text-xs text-text-tertiary">Plan a study session, clarify a topic, or find your next step</p></div><button className="dashboard-icon-button" aria-label="Open Conversation"><Icon name="arrow" /></button></div></DashboardCard>; }
